<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.gold.ordance</groupId>
    <artifactId>rgo-wm-spring</artifactId>
    <version>24.0.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <modules>
        <module>rgo-wm-spring-common</module>
        <module>rgo-wm-spring-jdbc</module>
        <module>rgo-wm-spring-web</module>
        <module>rgo-wm-spring-bom</module>
    </modules>

    <properties>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.source>17</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <rgo-wm-common-utils.version>24.0.0-SNAPSHOT</rgo-wm-common-utils.version>
        <spring-boot.version>3.3.0</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- bom -->
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>rgo-wm-common-utils-bom</artifactId>
                <version>${rgo-wm-common-utils.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- /bom -->
        </dependencies>
    </dependencyManagement>
</project>